name: Build NAO body

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: thesocialrobot/naobuild:main
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: debug
      shell: bash
      run: ls -laR
    - name: build desktop
      shell: bash
      run: make-desktop.sh
    - name: build robot
      shell: bash
      run: make-desktop.sh
