name: Build NAO body

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  # the image assumes HOME is /app, but GitHub actions sets it to be /github/home
  HOME: /app
  # build directoies take their names from toolchain
  # TODO replace scripts with use of context from build
  DESKTOP_OUT: body/build-naoqi-sdk/sdk/bin
  ROBOT_OUT: body/build-cross-atom/sdk/bin

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: thesocialrobot/naobuild:main
    steps:
    - uses: actions/checkout@v3
    - name: List qibuild configs
      shell: bash
      run: qibuild list-configs
    - name: Build desktop
      shell: bash
      run: ./make-desktop.sh
    - name: Archive desktop build output
      uses: actions/upload-artifact@v3
      with:
          name: desktop-binaries
          path: ${{ format('{0}/{1}', github.workspace, env.DESKTOP_OUT) }}
    - name: Build robot
      shell: bash
      run: ./make-robot.sh
    - name: Archive robot build output
      uses: actions/upload-artifact@v3
      with:
          name: robot-binaries
          path: ${{ format('{0}/{1}', github.workspace, env.ROBOT_OUT) }}
    - name: output debug
      shell: bash
      run: find ${{ github.workspace }} -name test_body -print
