name: Build NAO body

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  # the image assumes HOME is /app, but GitHub actions sets it to be /github/home
  HOME: /app

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: thesocialrobot/naobuild:main
    steps:
    - uses: actions/checkout@v3
    - name: configs
      shell: bash
      run: qibuild list-configs
    - name: build desktop
      shell: bash
      run: ./make-desktop.sh
    - name: build robot
      shell: bash
      run: ./make-robot.sh
