name: Build NAO body

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: thesocialrobot/naobuild:main
    steps:
    - uses: actions/checkout@v3
    - name: build desktop
      run: bash make-desktop.sh
    - name: build robot
      run: bash make-desktop.sh
